# SPDX-FileCopyrightText: (C) 2024, rick@vanosten.net, radi, portree_kid
# SPDX-License-Identifier: GPL-2.0-or-later
"""Stores all shared models, which are used by osm2city from the FG scenery database."""

DIR_MODELS_MISC = 'Models/Misc/'

# worship buildings - used in buildings_lib.py
BIG_CHURCH = DIR_MODELS_MISC + 'big-church.ac'
BRETON_CHURCH = DIR_MODELS_MISC + 'breton-church.ac'
CHURCH_36M_BLUE = DIR_MODELS_MISC + 'church36m_blue.ac'
CHURCH_36M_BLUE2 = DIR_MODELS_MISC + 'church36m_blue2.ac'
CHURCH_36M_GREEN = DIR_MODELS_MISC + 'church36m_green.ac'
CHURCH_36M_RED = DIR_MODELS_MISC + 'church36m_red.ac'
GEN_CHURCH_RD = DIR_MODELS_MISC + 'GenChurch_rd.ac'
GENERIC_CATHEDRAL = DIR_MODELS_MISC + 'generic_cathedral.ac'
GENERIC_CHURCH_01 = DIR_MODELS_MISC + 'generic_church_01.ac'
GENERIC_CHURCH_02 = DIR_MODELS_MISC + 'generic_church_02.ac'
GENERIC_CHURCH_03 = DIR_MODELS_MISC + 'generic_church_03.ac'
GOTHICAL_CHURCH = DIR_MODELS_MISC + 'gothical_church.ac'
ND_BOULOGNE = DIR_MODELS_MISC + 'NDBoulogne.ac'
ROMAN_CHURCH = DIR_MODELS_MISC + 'roman_church.ac'
ST_VAAST = DIR_MODELS_MISC + 'StVaast.ac'


# stuff in maritime.py

DIR_MODELS_MARITIME_CIVILIAN = 'Models/Maritime/Civilian/'

VESSEL_WOODEN_BOAT = DIR_MODELS_MARITIME_CIVILIAN + 'wooden_boat.ac'
VESSEL_WOODEN_BLUE_BOAT = DIR_MODELS_MARITIME_CIVILIAN + 'wooden_blue_boat.ac'
VESSEL_WOODEN_GREEN_BOAT = DIR_MODELS_MARITIME_CIVILIAN + 'wooden_green_boat.ac'
VESSEL_SMALL_RED_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'small-red-yacht.ac'
VESSEL_SMALL_BLACK_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'small-black-yacht.ac'
VESSEL_SMALL_CLEAR_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'small-clear-yacht.ac'
VESSEL_WIDE_BLACK_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'wide_black_yacht.ac'
VESSEL_WIDE_RED_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'wide_red_yacht.ac'
VESSEL_WIDE_CLEAR_YACHT = DIR_MODELS_MARITIME_CIVILIAN + 'wide_clear_yacht.ac'
VESSEL_BLUE_SAILING_BOAT_20M = DIR_MODELS_MARITIME_CIVILIAN + 'blue-sailing-boat-20m.ac'
VESSEL_RED_SAILING_BOAT_11M = DIR_MODELS_MARITIME_CIVILIAN + 'red-sailing-boat-11m.ac'
VESSEL_RED_SAILING_BOAT_20M = DIR_MODELS_MARITIME_CIVILIAN + 'red-sailing-boat-20m.ac'
VESSEL_MEDIUM_FERRY = DIR_MODELS_MARITIME_CIVILIAN + 'MediumFerry.ac'
VESSEL_LARGE_TRAWLER = DIR_MODELS_MARITIME_CIVILIAN + 'LargeTrawler.ac'
VESSEL_LARGE_FERRY = DIR_MODELS_MARITIME_CIVILIAN + 'LargeFerry.ac'
VESSEL_BARGE = DIR_MODELS_MARITIME_CIVILIAN + 'barge.ac'
VESSEL_SIMPLE_FREIGHTER = DIR_MODELS_MARITIME_CIVILIAN + 'SimpleFreighter.ac'
VESSEL_FERRY_BOAT_1 = DIR_MODELS_MARITIME_CIVILIAN + 'FerryBoat1.ac'

DIR_MODELS_MARITIME_MISC = 'Models/Maritime/Misc/'

SEAMARK_GREEN_BUOY = DIR_MODELS_MARITIME_MISC + 'GreenBuoy.ac'
SEAMARK_RED_BUOY = DIR_MODELS_MARITIME_MISC + 'RedBuoy.ac'
SEAMARK_BUOY_CONICAL_GREEN = DIR_MODELS_MARITIME_MISC + 'Buoy-Conical-Green.ac'
SEAMARK_BUOY_CYLINDRICAL_RED = DIR_MODELS_MARITIME_MISC + 'Buoy-Cylindrical-Red.ac'
SEAMARK_BUOY_CYLINDRICAL_YELLOW = DIR_MODELS_MARITIME_MISC + 'Buoy-Cylindrical-Yellow.ac'
SEAMARK_BUOY_SAFE_WATER = DIR_MODELS_MARITIME_MISC + 'Buoy-Safe-Water.ac'
SEAMARK_BUOY_ISOLATED_DANGER = DIR_MODELS_MARITIME_MISC + 'Buoy-IsolatedDanger.ac'
SEAMARK_BUOY_CARDINAL_NORTH = DIR_MODELS_MARITIME_MISC + 'Buoy-Cardinal-North.ac'
SEAMARK_BUOY_CARDINAL_EAST = DIR_MODELS_MARITIME_MISC + 'Buoy-Cardinal-East.ac'
SEAMARK_BUOY_CARDINAL_SOUTH = DIR_MODELS_MARITIME_MISC + 'Buoy-Cardinal-South.ac'
SEAMARK_BUOY_CARDINAL_WEST = DIR_MODELS_MARITIME_MISC + 'Buoy-Cardinal-West.ac'

# stuff in pylons

DIR_MODELS_INDUSTRIAL = 'Models/Industrial/'

# for gas
STORAGE_TANK_GENERIC_PRESSURE_VESSEL_10M = DIR_MODELS_INDUSTRIAL + 'GenericPressureVessel10m.ac'
STORAGE_TANK_GENERIC_PRESSURE_VESSEL_20M = DIR_MODELS_INDUSTRIAL + 'GenericPressureVessel20m.ac'
STORAGE_TANK_GENERIC_PRESSURE_VESSEL_30M = DIR_MODELS_INDUSTRIAL + 'GenericPressureVessel30m.ac'
STORAGE_TANK_GENERIC_PRESSURE_VESSEL_40M = DIR_MODELS_INDUSTRIAL + 'GenericPressureVessel40m.ac'
STORAGE_TANK_GASOMETER = DIR_MODELS_INDUSTRIAL + 'Gasometer.ac'
STORAGE_TANK_HC_TANK = DIR_MODELS_INDUSTRIAL + 'HC-Tank.ac'
# for other stuff
STORAGE_TANK_KOFF_TANK_10M = DIR_MODELS_INDUSTRIAL + 'KOFF_Tank_10M.ac'
STORAGE_TANK_KOFF_TANK_12M = DIR_MODELS_INDUSTRIAL + 'KOFF_Tank_12M.ac'
STORAGE_TANK_KOFF_TANK_13M = DIR_MODELS_INDUSTRIAL + 'KOFF_Tank_13M.ac'
STORAGE_TANK_KOFF_TANK_20M = DIR_MODELS_INDUSTRIAL + 'KOFF_Tank_20M.ac'
STORAGE_TANK_KOFF_TANK_30M = DIR_MODELS_INDUSTRIAL + 'KOFF_Tank_30M.ac'
STORAGE_TANK_API_65M = DIR_MODELS_INDUSTRIAL + '65m.ac'
STORAGE_TANK_AGIP_80M = DIR_MODELS_INDUSTRIAL + '80m.ac'

DIR_MODELS_AGRICULTURE = 'Models/Agriculture/'

SILO_8M = DIR_MODELS_AGRICULTURE + '1silo_8m.ac'
SILO_20M = DIR_MODELS_AGRICULTURE + '1silo_20m.ac'

CHIMNEY_BRICK_502M = DIR_MODELS_INDUSTRIAL + 'brick_chimney_502m.ac'
CHIMNEY_TPS_DRUJBA2 = DIR_MODELS_INDUSTRIAL + 'TPS_Drujba2_chimney.ac'
CHIMNEY_BOESDORF = DIR_MODELS_INDUSTRIAL + 'Boesdorf_Chimney.ac'
CHIMNEY_KW_ALTBACH = DIR_MODELS_INDUSTRIAL + 'kw_altbach_chimney250.ac'
CHIMNEY_GENERIC_01 = DIR_MODELS_INDUSTRIAL + 'generic_chimney_01.ac'

DIR_MODELS_POWER = 'Models/Power/'

WIND_TURBINE_VESTAS_BASE = DIR_MODELS_POWER + 'Vestas_Base.ac'
WIND_TURBINE_VESTAS_V80_SEA = DIR_MODELS_POWER + 'vestas-v80-sea.xml'
WIND_TURBINE_VESTAS_OFFSHORE_140M = DIR_MODELS_POWER + 'Vestas_Off_Shore140M.xml'
WIND_TURBINE_DEFAULT_FLASH = DIR_MODELS_POWER + 'windturbine_flash.xml'
WIND_TURBINE_DEFAULT = DIR_MODELS_POWER + 'windturbine.xml'
WIND_TURBINE_E82_78M = DIR_MODELS_POWER + 'windturbine_e82_78m.xml'
WIND_TURBINE_E82_85M = DIR_MODELS_POWER + 'windturbine_e82_85m.xml'
WIND_TURBINE_E82_98M = DIR_MODELS_POWER + 'windturbine_e82_98m.xml'
WIND_TURBINE_E82_108M = DIR_MODELS_POWER + 'windturbine_e82_108m.xml'
WIND_TURBINE_E82_138M = DIR_MODELS_POWER + 'windturbine_e82_138m.xml'
WIND_TURBINE_LAG18_18M_OBST = DIR_MODELS_POWER + 'windturbine_LAG18_18m_obst.xml'
WIND_TURBINE_LAG18_18M = DIR_MODELS_POWER + 'windturbine_LAG18_18m.xml'
WIND_TURBINE_LAG18_24M_OBST = DIR_MODELS_POWER + 'windturbine_LAG18_24m_obst.xml'
WIND_TURBINE_LAG18_24M = DIR_MODELS_POWER + 'windturbine_LAG18_24m.xml'
WIND_TURBINE_LAG18_30M_OBST = DIR_MODELS_POWER + 'windturbine_LAG18_30m_obst.xml'
WIND_TURBINE_LAG18_30M = DIR_MODELS_POWER + 'windturbine_LAG18_30m.xml'
WIND_TURBINE_LAG18_39M_OBST = DIR_MODELS_POWER + 'windturbine_LAG18_39m_obst.xml'
WIND_TURBINE_LAG18_39M = DIR_MODELS_POWER + 'windturbine_LAG18_39m.xml'

POWER_PYLON_WOODEN_POLE_14M = DIR_MODELS_POWER + 'wooden_pole_14m.ac'
POWER_PYLON_H_FRAME_STEEL_25M = DIR_MODELS_POWER + 'Transmission_25m_Steel_H.ac'
POWER_PYLON_H_FRAME_WOOD_25M = DIR_MODELS_POWER + 'Transmission_25m_Wood_H.ac'
POWER_PYLON_STEEL_SINGLE_30M = DIR_MODELS_POWER + 'Transmission_30m_Steel_Single.ac'
POWER_PYLON_GENERIC_PYLON_25M = DIR_MODELS_POWER + 'generic_pylon_25m.ac'
POWER_PYLON_GENERIC_PYLON_50M = DIR_MODELS_POWER + 'generic_pylon_50m.ac'
POWER_PYLON_GENERIC_PYLON_100M = DIR_MODELS_POWER + 'generic_pylon_100m.ac'

DIR_MODELS_COMMUNICATIONS = 'Models/Communications/'

COMMUNICATION_MAST_MIL_ANTENNA_45M = DIR_MODELS_COMMUNICATIONS + 'mil-antena-45m.ac'
COMMUNICATION_MAST_MIL_ANTENNA_61M = DIR_MODELS_COMMUNICATIONS + 'mil-antena-61m.ac'
# not using mil-antena-118m (base would start at 32 metres)
COMMUNICATION_MAST_CELL_MONO_1 = DIR_MODELS_COMMUNICATIONS + 'cell-monopole1-75m.ac'
COMMUNICATION_MAST_CELL_MONO_2 = DIR_MODELS_COMMUNICATIONS + 'cell-monopole2-75m.ac'
COMMUNICATION_MAST_CELL_MONO_3 = DIR_MODELS_COMMUNICATIONS + 'cell-monopole3-75m.ac'
COMMUNICATION_MAST_ANTENNA4 = DIR_MODELS_COMMUNICATIONS + 'Antenna4.ac'
COMMUNICATION_MAST_BASE_CLAPE_3 = DIR_MODELS_COMMUNICATIONS + 'base_clape_03.ac'
COMMUNICATION_MAST_BASE_CLAPE_4 = DIR_MODELS_COMMUNICATIONS + 'base_clape_04.ac'

DIR_MODELS_STREET_FURNITURE = 'Models/StreetFurniture/'

STREETLAMP_1 = DIR_MODELS_STREET_FURNITURE + 'Streetlamp1.ac'
STREETLAMP_2 = DIR_MODELS_STREET_FURNITURE + 'Streetlamp2.ac'
STREETLAMP_3 = DIR_MODELS_STREET_FURNITURE + 'Streetlamp3.ac'

RAIL_POWER_PYLON = DIR_MODELS_STREET_FURNITURE + 'RailPower.ac'
RAIL_STOP_TENSION = DIR_MODELS_STREET_FURNITURE + 'rail_stop_tension.ac'

DIR_MODELS_TRANSPORT = 'Models/Transport/'

AERIALWAY_DRAG_LIFT_PYLON = DIR_MODELS_TRANSPORT + 'drag_lift_pylon.ac'

# =============================================================================================
# shared models not yet used in osm2city - we still have them here, such that they get
# cleaned from stg-files and make space for osm2city placed shared objects or instanced objects

STORAGE_TANK_GENERIC_TANK_005M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_005m_brown.ac'
STORAGE_TANK_GENERIC_TANK_010M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_010m_brown.ac'
STORAGE_TANK_GENERIC_TANK_015M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_015m_brown.ac'
STORAGE_TANK_GENERIC_TANK_020M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_020m_brown.ac'
STORAGE_TANK_GENERIC_TANK_030M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_030m_brown.ac'
STORAGE_TANK_GENERIC_TANK_040M_BROWN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_040m_brown.ac'

STORAGE_TANK_GENERIC_TANK_005M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_005m_grey.ac'
STORAGE_TANK_GENERIC_TANK_010M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_010m_grey.ac'
STORAGE_TANK_GENERIC_TANK_015M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_015m_grey.ac'
STORAGE_TANK_GENERIC_TANK_020M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_020m_grey.ac'
STORAGE_TANK_GENERIC_TANK_030M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_030m_grey.ac'
STORAGE_TANK_GENERIC_TANK_040M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_040m_grey.ac'
STORAGE_TANK_GENERIC_TANK_050M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_050m_grey.ac'
STORAGE_TANK_GENERIC_TANK_075M_GREY_NOT_USED = DIR_MODELS_INDUSTRIAL + 'generic_tank_075m_grey.ac'

STORAGE_TANK_GENERIC_TANK_005M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank5m.ac'
STORAGE_TANK_GENERIC_TANK_010M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank10m.ac'
STORAGE_TANK_GENERIC_TANK_015M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank15m.ac'
STORAGE_TANK_GENERIC_TANK_020M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank20m.ac'
STORAGE_TANK_GENERIC_TANK_030M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank30m.ac'
STORAGE_TANK_GENERIC_TANK_040M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank40m.ac'
STORAGE_TANK_GENERIC_TANK_050M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank50m.ac'
STORAGE_TANK_GENERIC_TANK_075M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank75m.ac'
STORAGE_TANK_GENERIC_TANK_100M_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank100m.ac'

STORAGE_TANK_GENERIC_TANK_005M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank5m_black.ac'
STORAGE_TANK_GENERIC_TANK_010M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank10m_black.ac'
STORAGE_TANK_GENERIC_TANK_015M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank15m_black.ac'
STORAGE_TANK_GENERIC_TANK_020M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank20m_black.ac'
STORAGE_TANK_GENERIC_TANK_030M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank30m_black.ac'
STORAGE_TANK_GENERIC_TANK_040M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank40m_black.ac'
STORAGE_TANK_GENERIC_TANK_050M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank50m_black.ac'
STORAGE_TANK_GENERIC_TANK_075M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank75m_black.ac'
STORAGE_TANK_GENERIC_TANK_100M_BLACK_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank100m_black.ac'

STORAGE_TANK_GENERIC_TANK_005M_ORANGE_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank5m_orange.ac'
STORAGE_TANK_GENERIC_TANK_010M_ORANGE_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank10m_orange.ac'

STORAGE_TANK_GENERIC_TANK_030M_YELLOW_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank30m_yellow.ac'
STORAGE_TANK_GENERIC_TANK_040M_YELLOW_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank40m_yellow.ac'
STORAGE_TANK_GENERIC_TANK_050M_YELLOW_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank50m_yellow.ac'

STORAGE_TANK_GENERIC_TANK_005M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank5m_light_green.ac'
STORAGE_TANK_GENERIC_TANK_010M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank10m_light_green.ac'  # does not exist - but for consistency
STORAGE_TANK_GENERIC_TANK_015M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank15m_light_green.ac'
STORAGE_TANK_GENERIC_TANK_020M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank20m_light_green.ac'
STORAGE_TANK_GENERIC_TANK_030M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank30m_light_green.ac'
STORAGE_TANK_GENERIC_TANK_040M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank40m_light_green.ac'
STORAGE_TANK_GENERIC_TANK_050M_LIGHT_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank50m_light_green.ac'

STORAGE_TANK_GENERIC_TANK_005M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank5m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_010M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank10m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_015M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank15m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_020M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank20m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_030M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank30m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_040M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank40m_dark_green.ac'
STORAGE_TANK_GENERIC_TANK_050M_DARK_GREEN_NOT_USED = DIR_MODELS_INDUSTRIAL + 'GenericStorageTank50m_dark_green.ac'


WIND_TURBINE_ENERCON_E126_NOT_USED = DIR_MODELS_POWER + 'Enercon_E-126.xml'
WIND_TURBINE_TOW_BLADE_NOT_USED = DIR_MODELS_POWER + 'twobladeturbine.xml'
WIND_TURBINE_V126_200M_NOT_USED = DIR_MODELS_POWER + 'V126-200m.xml'
WIND_TURBINE_VESTAS_OFFSHORE_140M2_NOT_USED = DIR_MODELS_POWER + 'Vestas_Off_Shore140M2.xml'
WIND_TURBINE_VESTAS_V80_NOT_USED = DIR_MODELS_POWER + 'vestas-v80.xml'
WIND_TURBINE_E3120_24M_NOT_USED = DIR_MODELS_POWER + 'windturbine_E3120_24m.xml'
WIND_TURBINE_G80_110M_NOT_USED = DIR_MODELS_POWER + 'windturbine_G80_110m.xml'
WIND_TURBINE_V112_ONSHORE_NOT_USED = DIR_MODELS_POWER + 'windturbine_V112_onshore.xml'
WIND_TURBINE_WES18_18M_OBST_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_18m_obst.xml'
WIND_TURBINE_WES18_18M_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_18m.xml'
WIND_TURBINE_WES18_24M_OBST_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_24m_obst.xml'
WIND_TURBINE_WES18_24M_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_24m.xml'
WIND_TURBINE_WES18_30M_OBST_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_30m_obst.xml'
WIND_TURBINE_WES18_30M_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_30m.xml'
WIND_TURBINE_WES18_39M_OBST_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_39m_obst.xml'
WIND_TURBINE_WES18_39M_NOT_USED = DIR_MODELS_POWER + 'windturbine_WES18_39m.xml'
WIND_TURBINE_D90T_105M_NOT_USED = DIR_MODELS_POWER + 'wtD90T105m.xml'

POWER_PYLON_25M_WOOD_TRIPLE_NOT_USED = DIR_MODELS_POWER + 'Transmission_25m_Wood_Triple.ac'
POWER_PYLON_25M_WOOD_TRIPLE_H_NOT_USED = DIR_MODELS_POWER + 'Transmission_25m_Wood_TripleH.ac'
